AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'lib/repository/storage/db/**/*'
    - 'config/**/*'
    - 'Rakefile'

Metrics/MethodLength:
  Max: 10

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '**/*.rake'
